dist: focal
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  artifacts:
    # ...
    paths:
      - $(git ls-files -o | grep travis_artifacts | tr "\n" ":")

language: php

php:
  - 8.0

env:
  global:
    # Travis Token.
    secure: "u6jLZiftQdb8Ozxngu5sgwmnXeUyvNF3/Y+5eX3+Xyb7Sm6K++cBLbYl/zNbuzp1rZE5dn3pVTQc4tstVXZw2B5KjCd64r9HE9gdwCEnS/AA/w3wGlaEBinTzKOrrN1EvqNNhnJUY2JmqEYVom+UYwLZWIIKM/5OoaeidNqHDvImZZLAeYfPMGnySsFC01yCzrOn6jv8Bwu00dQPVEOQylVEV5qgdGYz6CvGGslcvGxhvR0qdY/IXhrA0yxIk1yA6vu1mQpCSjGpPLy024JhcqRr3AzjH2N0QRKlL7vcNFxl/OC0qcK2bOl8lcQydeC5LRp92eeCLfMfvqHDqLJKvebCsvaZSmqlzCURlcHaJOM5bce7XPVyNLdwnfppgSacocGol38qxfEc09qV4AZnklwigYCfnk346oSaocKApy48KRW4cNXL45U7+z10IzVAENGwbyyuwdvKHhDtMCgMd8eeYfRF5EvENOKVSG02Kca8X2fLBhmJsXkFcBEW7pSRZKxixkIkuAwEYSQW/lvvM4LJmd2np7vZDEMh1dmf7TBRBygDVmM7vtdYRSzivR/T9nH+mXPP9FcjVvlPPeWAEaqtLPmmONmYRjDRcoHjJh3YnSMpvVs8wejDf7iS6A44cI6xZQRoEoCFA/WUu5EnzmoOCY7HvZ62xnZ0I9nNyL4="

services:
  - docker

before_install:
  - set -e
  # Composer Configurations.
  - export COMPOSER_MEMORY_LIMIT=-1 # Set php memory limit to -1 so composer update will not fail
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1 # To enforce throwing an error and stopping package installation/update immediately
  - phpenv config-rm xdebug.ini

  # Travis self-updates it's PHP and Composer dependencies every 30-60 days, so it automatically updates to version 2
  - composer install --prefer-dist --no-interaction
  # Install docker and our docker containers.
  - sh scripts/social/ci/install-docker.sh
  - docker compose -f docker-compose-ci.yml up -d

script:
  - docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh
  - docker exec -i social_ci_web_scripts /var/www/scripts/social/run-tests.sh --testsuite social
  - docker exec -it social_ci_behat sh /var/www/scripts/social/behatstability.sh stability-1
