services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      - VIRTUAL_HOST=social.local
      - DRUPAL_SETTINGS=development
    ports:
      - "80"
    container_name: social_web

  db:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    container_name: social_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.social.local
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    container_name: social_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    depends_on:
      - web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: social_selenium

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
    environment:
      - DRUPAL_SETTINGS=development
    container_name: social_behat

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
    environment:
      - DRUPAL_SETTINGS=development
    container_name: social_cron

  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os_solr_data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      - SOLR_SOLR_MEM_SIZE=512m
      - PARTIAL_SEARCH_ENABLED=false
      - VIRTUAL_HOST=solr.social.local
      - VIRTUAL_PORT=8983
    ports:
      - "8983"
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: social_solr

  redis:
    image: redis:latest

volumes:
  db_data:
  os_solr_data:
