# See: https://docs.docker.com/compose/compose-file/
# See: https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      DRUPAL_SETTINGS: development
      VIRTUAL_HOST: "${PROJECT_BASE_URL}"
      VIRTUAL_PORT: 80
    ports:
      - "80"
    container_name: "${PROJECT_NAME}_web"

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
    volumes:
      - db_data:/var/lib/mysql
    container_name: "${PROJECT_NAME}_db"
    command: mysqld --max_allowed_packet=16M
    ports:
      - "3306"

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: "mailcatcher.${PROJECT_BASE_URL}"
      VIRTUAL_PORT: 1080
    ports:
      - "1080"
    container_name: "${PROJECT_NAME}_mailcatcher"

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    depends_on:
      - web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: "${PROJECT_NAME}_selenium"

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
    environment:
      - DRUPAL_SETTINGS=development
    container_name: "${PROJECT_NAME}_behat"

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
    environment:
      - DRUPAL_SETTINGS=development
    container_name: "${PROJECT_NAME}_cron"

  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os_solr_data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      SOLR_SOLR_MEM_SIZE: 512m
      PARTIAL_SEARCH_ENABLED: 0
      VIRTUAL_HOST: "solr.${PROJECT_BASE_URL}"
      VIRTUAL_PORT: 8983
    ports:
      - "8983"
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: "${PROJECT_NAME}_solr"

  redis:
    image: redis:latest
    container_name: "${PROJECT_NAME}_redis"
    ports:
      - "6379"

volumes:
  db_data:
  os_solr_data:

networks:
  # Default will connect all containers to the specified network.
  default:
    # Network name.
    name: nginx
    # Connects to an existing network.
    external: true
