# See: https://docs.docker.com/compose/compose-file/
# See: https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  web_scripts:
    image: goalgorilla/open_social_docker:ci
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
    environment:
      - DRUPAL_SETTINGS=production
    container_name: social_ci_web_scripts

  web:
    image: goalgorilla/open_social_docker:ci
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      - DRUPAL_SETTINGS=production
    ports:
      - "80"
    container_name: social_ci_web

  db:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"
    container_name: social_ci_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.social.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    container_name: social_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    depends_on:
      - web
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: social_ci_selenium

  behat:
    image: goalgorilla/open_social_docker:ci
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
      - mailcatcher
    environment:
      - DRUPAL_SETTINGS=production
    container_name: social_ci_behat

  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os-solr-data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      - SOLR_SOLR_MEM_SIZE=512m
      - PARTIAL_SEARCH_ENABLED=false
      - VIRTUAL_HOST=solr.social.local
      - VIRTUAL_PORT=8983
    ports:
      - "8983"
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: social_ci_solr

  redis:
    image: redis:latest

volumes:
  db-data:
  os-solr-data:
