# See: https://docs.docker.com/compose/compose-file/
# See: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# See: https://docs.docker.com/compose/cli-command-compatibility/
services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      VIRTUAL_HOST: social.localhost
      DRUPAL_SETTINGS: development
    ports:
      - "80"
    container_name: social-web

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"
    container_name: social-db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: mailcatcher.social.localhost
      VIRTUAL_PORT: 1080
    ports:
      - "1080"
    container_name: social-mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    depends_on:
      - web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: social-selenium

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
    environment:
      DRUPAL_SETTINGS: development
    container_name: social-behat

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
    environment:
      DRUPAL_SETTINGS: development
    container_name: social-cron

  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os-solr-data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      SOLR_SOLR_MEM_SIZE: 512m
      PARTIAL_SEARCH_ENABLED: false
      VIRTUAL_HOST: solr.social.localhost
      VIRTUAL_PORT: 8983
    ports:
      - "8983"
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: social-solr

  redis:
    image: redis:latest

volumes:
  db-data: {}
  os-solr-data: {}
