version: "2"

services:
  web:
    image: goalgorilla/drupal_social
    links:
      - db:db
    ports:
      - "80"
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"

  db:
    image: mysql:5.6
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=social
    volumes:
     - db_data:/var/lib/mysql
    network_mode: "bridge"

volumes:
  db_data:
