version: "2"

services:
  web:
    build: docker_build/drupal8/development
    volumes:
     - ./public_html:/var/www/html
     - ./dev-scripts/:/root/dev-scripts
    links:
     - db
     - mailcatcher
    environment:
     - VIRTUAL_HOST=social.dev
     - DRUPAL_SETTINGS=development
    ports:
     - "80"
    network_mode: "bridge"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.social.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"

# Currently disabled because of rate limits.
# Enable and use the normal ssmtp.conf file to sent emails with postfix.
#mailserver:
#  image: marvambass/versatile-postfix
#  environment:
#    - ALIASES=postmaster:root;hostmaster:root;webmaster:root
#  ports:
#    - "25"
#  command: social.dev user:password
  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    container_name: social_selenium
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"

  behat:
    build: docker_build/drupal8/development
    container_name: social_behat
    volumes:
     - ./public_html/:/var/www/html
     - ./dev-scripts/:/root/dev-scripts
     - ./behat/:/root/behat
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"

volumes:
  db_data: